export const WORDS = [
  'REACT', 'CHESS', 'MAPLE', 'CRANE', 'SLATE', 'ADIEU', 'AUDIO', 'HOUSE',
  'PLANT', 'SMILE', 'BREAD', 'LIGHT', 'WATER', 'BEACH', 'MUSIC', 'CLOUD',
  'DREAM', 'PEACE', 'STORM', 'QUIET', 'BRAVE', 'SHINE', 'FRESH', 'MAGIC',
  'POWER', 'SWEET', 'GRACE', 'STORY', 'CHARM', 'FLAME', 'SPACE', 'TRUTH',
  'HEART', 'CLEAR', 'SPARK', 'FIELD', 'GLORY', 'DANCE', 'OCEAN', 'FAITH',
  'TIGER', 'MOUNT', 'RIVER', 'ANGEL', 'LUCKY', 'PEARL', 'ROYAL', 'SMART',
  'HAPPY', 'WORLD', 'GIANT', 'YOUNG', 'QUICK', 'SOLID', 'SHARP', 'FRESH'
]